apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: nginx

spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 6
  template:
    metadata:
      name: nginx-2
      labels:
        app: nginx

    spec:
      containers:
        - name: nginx2
          image: nginx

    