apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp

spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      name: nginx-2
      labels:
        app: nginx

    spec:
      containers:
        - name: nginx2
          image: nginx

    